[package]
name = "ln_drawer"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = "1.23.2"
env_logger = "0.11.8"
glam = "0.30.5"
log = "0.4.27"
palette = "0.7.6"
pollster = "0.4.0"
tokio = "1.47.1"
wgpu = "26.0"
winit = "0.30"
