name: Test

on:
  push:
    branches:
      - dev
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  test-linux:
    name: Cargo Test x86_64 Linux
    runs-on: ubuntu-latest

    steps:
    - name: '[Actions] Checkout'
      uses: actions/checkout@v6

    - name: '[Actions] Cache'
      uses: actions/cache@v5
      with:
        key: ubuntu-all-cross-test-${{ hashFiles('Cargo.lock') }}
        restore-keys: |
          ubuntu-all-cross-test-
          ubuntu-all-cross-
        path: |
          ~/.cargo
          target

    - name: '[Install] ALSA Library'
      run: sudo apt-get install libasound2-dev

    - name: '[Test] Cargo Test x86_64 Linux'
      run: cargo test --verbose

  rustfmt-check:
    name: Format Check
    runs-on: ubuntu-latest
  
    steps:
    - name: '[Actions] Checkout'
      uses: actions/checkout@v6

    - name: '[Test] Cargo Fmt'
      run: cargo fmt --all --check
